### ISSUE TITLE
Implement missing CRUD CLI commands

### ISSUE THREAD

**Issue by adrianbenavides** [build-trust/ockam#4418]
### Current behavior

There are some CRUD commands missing, mostly related to the TCP resources (inlets/outlets/connections, ...).

### Desired behavior

Commands to implement:

- [x] `tcp-listener show`: https://github.com/build-trust/ockam/issues/4419
- [x] `tcp-listener delete`: https://github.com/build-trust/ockam/issues/4367
- [x] `tcp-connection show`: https://github.com/build-trust/ockam/issues/4420
- [x] `tcp-inlet show`: https://github.com/build-trust/ockam/issues/4421
- [x] `tcp-inlet delete`: https://github.com/build-trust/ockam/issues/4269
- [x] `tcp-outlet show`: https://github.com/build-trust/ockam/issues/4435
- [x] `tcp-outlet delete`: https://github.com/build-trust/ockam/issues/4268
- [x] `tcp-outlet list`: https://github.com/build-trust/ockam/issues/4228
- [x] `forwarder show`: https://github.com/build-trust/ockam/issues/4436
- [x] `forwarder delete`: https://github.com/build-trust/ockam/issues/4437
- [x] `forwarder list`: https://github.com/build-trust/ockam/issues/4441
- [x] `secure-channel-listener show`: https://github.com/build-trust/ockam/issues/4439
- [x] `secure-channel-listener delete`: https://github.com/build-trust/ockam/issues/4438

**Comment by nidnogg** [comment]
`tcp-inlet delete` should be close to completion at https://github.com/build-trust/ockam/pull/4433

**Comment by nidnogg** [comment]
`tcp-inlet show` and `tcp-outlet show` should be ready to review at https://github.com/build-trust/ockam/pull/4446

**Comment by nidnogg** [comment]
`forwarder show` and `forwarder list` recently merged from https://github.com/build-trust/ockam/issues/4436

**Comment by SanjoDeundiak** [comment]
Hey @nidnogg , was `forwarder delete` added anywhere? I don't see it

**Comment by adrianbenavides** [comment]
I think he meant `forwarder list`. The `delete` command was picked up by @h20220145
